import logging


def locality(name):
    dictionary = {
        "Челябинск": [55.159897, 61.402554],
        "Металлургический район": [55.2422888, 61.3769466],
        "Советский район": [55.11834, 61.3833043],
        "Курчатовский район": [55.217844, 61.3258543],
        "Тракторозаводской район": [55.172073, 61.4641043],
        "Калининский район": [55.188207, 61.416137],
        "Ленинский район": [55.120147, 61.479263],
        "Центральный район": [55.160767, 61.364250],
        "Троицк": [54.082761, 61.558989],
        "Коркино": [54.89258219629243, 61.390529810909925],
        "Кыштым": [55.71031976408574, 60.53947258542139],
        "Долгодеревенское": [55.349097577360105, 61.335827696313864],
        "Озерск": [55.76397473157817, 60.70426750729638],
        "Чебаркуль": [54.97981391504042, 60.36705260725639],
        "Копейск": [55.11734848799998, 61.61176079838372]
                  }
    try:
        return dictionary[name]
    except Exception as exc:
        logging.warning(exc)
        return 0, 0